Repository adamLutPhi/MachineLearner, pull requests merged in 2023-07, with the labels that each got.

#96 Update: Lec 29 `RBF - Regularization`
  src/Neural Network2.xmind
Labels: documentation, enhancement

#97 Update `FUNDING.yml`
  .github/FUNDING.yml
Labels: documentation

#98 Update README.md
  README.md
Labels: documentation

#99 Update: Lec 30 Difference between `MLP` , `RBF`
  src/Neural Network2.xmind
Labels: documentation, enhancement

#100 Update: add Lec 31 Learning Mechanism in RBF
  src/Neural Network2.xmind
Labels: documentation, enhancement

#103 Add: `gradientApprox`
  src/1.MachineLearning/Algorithm/gradientApprox.py
Labels: enhancement, help wanted, good first issue

#101 Add: `gradientApprox`
  src/1.MachineLearning/Algorithm/gradientApprox.py
Labels: enhancement, help wanted, good first issue
